meta:
  name: offerbox_scout_generator_requirements
  version: "1.0.0"
  purpose: >
    OfferBoxからコピーした学生プロフィール全文（paste_text）を入力として、
    アプリ側でA/B判定（自己PR候補200文字以上= A / 未満= B）を行い、
    Geminiには「本人向けオリジナリティPR要約（200〜300文字、最大300文字）」のみを生成させる。
    生成した要約を固定テンプレ（A or B）へ差し込み、スマホで読みやすい改行（1行30文字以内をなるべく）で
    スカウト文を完成させる。
  notes:
    - APIキーは要件定義/プロンプトに含めない（環境変数等で別途設定）
    - テンプレ本文はアプリ側に固定保持し、Geminiには送らない（トークン節約＆文面固定）
    - 個人特定情報（氏名/住所/電話/メール/学籍番号/SNS ID等）は出力に含めない
    - 深い推論より速度優先で良い
    - 本システムからOfferBoxへ送信はしない（コピー→OfferBox貼り付け→OfferBox送信）
    - ただし運用上「コピー＝送信扱い」とみなし、コピー押下で履歴レコードを追加する

scope:
  in_scope:
    - "新規レコード作成（貼り付け欄）"
    - "貼り付け内容から大学/学部/性別を抽出（失敗時は空欄OK）"
    - "自己PR候補の文字数200以上でA、未満でB（アプリ側判定）"
    - "Geminiで要約（200〜300文字、最大300文字）生成"
    - "テンプレA/Bに要約を差し込み、スカウト文を生成"
    - "スマホ向け改行整形（1行30文字以内をなるべく）"
    - "コピーボタンでクリップボードコピー＋履歴レコード追加"
    - "履歴の検索：期間（from/toカレンダー）＋フリーワード"
    - "CSV出力：現在表示中レコードのみ"
  out_of_scope:
    - "OfferBoxへの送信機能"
    - "OfferBox送信結果の連携"
    - "高度な推論による長文生成（速度優先）"

inputs:
  paste_text:
    type: string
    description: "OfferBoxからコピーして貼り付けた全文テキスト（生テキスト）"
  threshold_chars:
    type: integer
    fixed: 200
    description: "A/B判定のしきい値（自己PR候補文字数）"
  constraints:
    summary_char_min: 200
    summary_char_max: 300
    summary_char_hard_max: 300
    line_char_target: 30
    line_char_policy: "なるべく守る（多少の超過は許容）"

ui_requirements:
  create_record_screen:
    required:
      - "新規レコード作成ボタン"
      - "大きめ貼り付け欄（ドラッグ&ドロップ枠風の見た目、テキスト貼り付け用途）"
      - "文書作成ボタン"
      - "生成文プレビュー（改行多め、スマホ視認性重視）"
      - "コピーボタン（コピー＋履歴追加）"
    optional:
      - "A/B判定結果の表示"
      - "抽出項目（大学/学部/性別）の表示"
  history_screen:
    required:
      - "レコード一覧（表）"
      - "期間指定（from/to）カレンダー"
      - "フリーワード検索（期間絞り込み + フリーワード併用）"
      - "CSV書き出しボタン（表示中のみ）"
    columns_minimum:
      - "sent_date（コピー日）"
      - "sent_time（コピー時間）"
      - "pattern（A/B）"
      - "university"
      - "faculty"
      - "gender"

app_side_design:
  goal: "Geminiへの入出力トークン削減とテンプレ固定"
  responsibilities:
    - "paste_textの保存（raw_paste_textとして保持）"
    - "自己PR候補抽出（見出し検出→ブロック抽出／無ければ長文段落）"
    - "自己PR候補文字数をカウントし、200文字以上ならA、未満ならB"
    - "Geminiへは要約生成のみ依頼（JSONでsummaryのみ返す）"
    - "固定テンプレ（A or B）へ{summary}を差し込み message を生成"
    - "スマホ向け改行整形（1行30文字以内をなるべく）"
    - "コピー押下でクリップボードへコピー＋履歴レコード追加（コピー＝送信扱い）"
    - "抽出失敗（大学/学部/性別）は空欄で保存OK"
    - "履歴検索：期間（from/to）＋フリーワード"
    - "CSV出力：表示中（検索適用後）レコードのみ"

ab_judgement_app_side:
  pr_candidate_extraction:
    headings:
      - "自己PR"
      - "PR"
      - "アピール"
      - "強み"
      - "学生時代に力を入れたこと"
      - "ガクチカ"
      - "経験"
      - "実績"
      - "活動"
    method:
      - "上記見出し語を含む行を見つけたら、その次行以降を自己PR候補とする"
      - "次の見出しっぽい行または空行連続でブロック終了（簡易でOK）"
      - "見出しが見つからない場合は、空行区切り段落のうち最長段落を自己PR候補とする"
    char_count:
      rule: "Array.from()等で文字数カウント（日本語対応）"
  decision_rule:
    - if: "len(pr_candidate) >= 200"
      pattern: "A"
    - else:
      pattern: "B"

gemini_integration:
  objective: "本人向けオリジナリティPR要約（200〜300文字、最大300文字）を生成する"
  output_contract:
    must_be_json_only: true
    schema:
      type: object
      required: ["summary"]
      properties:
        summary:
          type: string
  system_instruction:
    text: |
      あなたは新卒スカウト文作成の編集者です。
      必ず日本語で出力してください。
      個人特定情報（氏名・住所・電話番号・メールアドレス・学籍番号・SNS ID等）を出力に含めません。
      事実不明の創作はしません（入力テキストにない経験・実績は書かない）。
      誇張表現（例：必ず成功、トップレベル等）は避けます。
      出力は必ずJSONのみで、指定キー以外は出力しません。
  user_instruction_template:
    text: |
      【タスク】
      以下のOfferBox貼り付けテキストから、本人の特徴を要約してください。

      【要約条件】
      - 200〜300文字（最大300文字）。300文字を超えたら必ず短くする
      - 2〜3文を推奨
      - 具体エピソードを最低1つ入れる（可能なら）
      - 断定しすぎない自然な表現（例：〜の傾向、〜な方、〜が得意そう 等）
      - テンプレ内で「『**要約**』だと感じ、」に接続する想定なので、つながりが自然な文章にする
      - 個人特定情報は出さない
      - 事実不明の創作はしない

      【出力】
      JSONで {"summary":"..."} のみを返す（JSON以外の文字を出さない）。

      【入力テキスト】
      <<<PASTE_TEXT>>>
      {paste_text}
  generation_config_recommendation:
    temperature: 0.4
    max_output_tokens: 256
    response_mime_type: "application/json"
    response_schema:
      type: object
      required: ["summary"]
      properties:
        summary:
          type: string

templates_app_side:
  insertion_rule:
    placeholder: "{summary}"
    replacement: "summary（Gemini生成）"
    style:
      - "テンプレ内では **{summary}** として太字維持"
      - "テンプレ文章『…だと感じ、』につながるように自然なsummaryを期待"
  template_A: |
    【人の強みを引き出せるあなたへ】
    初めまして。
    スタートライン新卒採用責任者の船戸です。

    プロフィールを拝見し、
    「**{summary}**」だと感じ、
    ぜひ一度お話したく
    ご連絡しました！

    ＼当社を一言で言うと…／
    「人と企業をつなぐ
    HRソリューション企業」です。
    （採用～定着～活躍までを支援）

    この仕事の面白さは、
    人の強みを見つけて、
    活躍の場をつくれること。

    ---------------------------
    ✔成長をサポートしたい
    ✔「ありがとう」がやりがいに
    ✔誰かの可能性を広げたい
    ---------------------------

    1つでも当てはまったら
    当社の仕事、
    向いているかもしれません！

    是非、カジュアル面談で
    ざっくばらんに
    お話できれば嬉しいです！

    承諾＝応募ではありませんので
    就活相談だけでも大丈夫です。
    ※希望者には、
    会社説明会（WEB）のご案内も◎

    ＼働きやすさも整っています／
    ・年休120日以上/残業少なめ
    ・手厚い研修制度が自慢◎
    ・ジョブローテーション制度あり
    （本社勤務など実績多数あり）

    お話できるのを
    楽しみにしています！

    株式会社スタートライン
    新卒採用責任者　船戸
  template_B: |
    【就活相談OK｜カジュアル面談】
    初めまして。
    スタートライン新卒採用責任者の船戸です。

    プロフィールを拝見し、
    「**{summary}**」だと感じ、
    ぜひ一度お話したく
    ご連絡しました！

    就活のこの時期、
    こんな気持ちになること
    ありませんか？

    ---------------------------
    ・何が向いているのか分からない
    ・業界が絞れず、情報収集で疲れる
    ・納得感をもって就活を進めたい
    ---------------------------

    今回のオファーは
    いきなり選考のご案内ではありません。
    まずは【20分のカジュアル面談（WEB）】で、
    気軽にお話できればと思っています。

    ＼当社を一言で言うと…／
    「人と企業をつなぐ
    HRソリューション企業」です。

    この仕事の面白さは、
    人の強みを見つけて
    活躍の場をつくれること。

    ---------------------------
    ✔成長をサポートしたい
    ✔「ありがとう」がやりがいに
    ✔誰かの可能性を広げたい
    ---------------------------

    1つでも当てはまったら
    当社の仕事、
    向いているかもしれません！

    【承諾＝選考ではありません】
    話を聞いてから決めたい、
    就活相談だけしたい、でもOKです。
    ※希望者には、
    会社説明会（WEB）のご案内も可能です◎

    承諾いただけたら、
    こちらから日程候補をお送りします。

    ＼働きやすさも整っています／
    ・年休120日以上/残業少なめ
    ・手厚い研修制度が自慢◎
    ・ジョブローテーション制度あり
    （本社勤務など実績多数あり）

    お話できるのを
    楽しみにしています！

    株式会社スタートライン
    新卒採用責任者　船戸

formatting_rules_app_side:
  message_line_break:
    intent: "スマホで見やすい改行"
    rules:
      - "1行あたり30文字以内をなるべく守る（多少の超過は許容）"
      - "意味の切れ目（読点、助詞、句点、記号）で改行する"
      - "区切り線/チェック/太字などの装飾はテンプレ通り維持"
  summary_sanity_checks:
    rules:
      - "200〜300文字内に収める（>300はNG）"
      - "個人特定情報らしきものが含まれる場合は再生成またはマスク"
      - "空/短すぎる場合は再生成（B寄りの汎用要約で可）"

history_requirements_app_side:
  record_policy:
    trigger: "コピー押下"
    meaning: "コピー＝送信扱い"
    raw_paste_text_storage: true
  required_fields:
    - sent_date   # コピー日（YYYY-MM-DD）
    - sent_time   # コピー時刻（HH:mm:ss等）
    - pattern     # A/B
    - university  # 抽出失敗時は空欄でOK
    - faculty     # 抽出失敗時は空欄でOK
    - gender      # 抽出失敗時は空欄でOK
  search_ui:
    required:
      - date_range_calendar: "from/to（いつからいつ）"
      - free_word_search: "期間絞り込み + フリーワードを併用"
  csv_export:
    behavior: "現在表示中（期間＋検索適用後）のレコードのみを書き出す"
    columns:
      - sent_date
      - sent_time
      - pattern
      - university
      - faculty
      - gender
